/**
 * GOODWIN OUTPUT GENERATOR
 * Reads the master chairs catalog and writes ready-to-paste output for
 * the two Goodwin files that need chair data:
 *
 *   1. goodwin-quiz-page.js  → CHAIR_URLS and CHAIR_IMAGES objects
 *   2. goodwin-chat-backend/server.js → ## COMPLETE CHAIR CATALOG section
 *
 * HOW TO RUN:
 *   From the massagechairfinder/ directory:
 *   npm run generate-goodwin
 *
 *   Output is written to scripts/goodwin-output/ and also printed to the console.
 *
 * AFTER RUNNING:
 *   1. Open scripts/goodwin-output/goodwin-quiz-objects.js
 *      → Copy CHAIR_URLS into goodwin-quiz-page.js (replace existing CHAIR_URLS const)
 *      → Copy CHAIR_IMAGES into goodwin-quiz-page.js (replace existing CHAIR_IMAGES const)
 *   2. Open scripts/goodwin-output/goodwin-catalog.txt
 *      → Copy the text block into goodwin-chat-backend/server.js
 *        (replace everything from "## COMPLETE CHAIR CATALOG" to the end of QUIZ_PROMPT)
 *   3. Commit both files in their respective repos.
 */

import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { GOODWIN_CHAIRS, buildGoodwinCatalogText, getGoodwinLookupChairs } from '../lib/catalogText.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outputDir = join(__dirname, 'goodwin-output')

mkdirSync(outputDir, { recursive: true })

// ─── 1. CHAIR_URLS ─────────────────────────────────────────────────────────────

const lookupChairs = getGoodwinLookupChairs()

const chairUrlsLines = lookupChairs.map(chair => {
  const url = chair.affiliateUrl ?? ''
  const comment = !url ? '  // TODO: add affiliate URL' : ''
  return `  '${chair.goodwinLookupKey}':${' '.repeat(Math.max(1, 44 - (chair.goodwinLookupKey?.length ?? 0)))}${url ? `'${url}'` : "''"},${comment}`
})

const chairUrlsBlock = [
  '// ─── CHAIR URL LOOKUP ────────────────────────────────────────────────────────',
  '// Auto-generated by scripts/generate-goodwin.ts — do not edit manually.',
  '// Maps chair names (lowercase, partial match) to affiliate URLs.',
  '// Order matters: more specific keys (e.g. lm-6800s) must come before less',
  '// specific ones (e.g. lm-6800) to prevent partial-match collisions.',
  '//',
  '// To update: edit massagechairfinder/lib/chairs.ts, then run npm run generate-goodwin.',
  'const CHAIR_URLS = {',
  ...chairUrlsLines,
  '};',
].join('\n')

// ─── 2. CHAIR_IMAGES ───────────────────────────────────────────────────────────

const chairImagesLines = lookupChairs.map(chair => {
  const url = chair.goodwinImageUrl ?? ''
  const comment = !url ? '  // TODO: upload image to Shopify Files and paste CDN URL here' : ''
  return `  '${chair.goodwinLookupKey}':${' '.repeat(Math.max(1, 44 - (chair.goodwinLookupKey?.length ?? 0)))}${url ? `'${url}'` : "''"},${comment}`
})

const chairImagesBlock = [
  '// ─── CHAIR IMAGE LOOKUP ──────────────────────────────────────────────────────',
  '// Auto-generated by scripts/generate-goodwin.ts — do not edit manually.',
  '// Maps chair names (lowercase, partial match) to Shopify CDN image URLs.',
  '//',
  '// To add a new image: upload the file to Shopify Admin → Content → Files,',
  '// copy the CDN URL, then update goodwinImageUrl in massagechairfinder/lib/chairs.ts',
  '// and re-run npm run generate-goodwin.',
  'const CHAIR_IMAGES = {',
  ...chairImagesLines,
  '};',
].join('\n')

// ─── WRITE quiz objects file ────────────────────────────────────────────────────

const quizObjectsContent = [
  '/**',
  ' * GOODWIN QUIZ PAGE — Chair URL and Image Objects',
  ' * Auto-generated by massagechairfinder/scripts/generate-goodwin.ts',
  ' *',
  ' * HOW TO USE:',
  ' *   Copy CHAIR_URLS and CHAIR_IMAGES into goodwin-quiz-page.js,',
  ' *   replacing the existing const declarations for each.',
  ' */',
  '',
  chairUrlsBlock,
  '',
  chairImagesBlock,
].join('\n')

const quizObjectsPath = join(outputDir, 'goodwin-quiz-objects.js')
writeFileSync(quizObjectsPath, quizObjectsContent, 'utf-8')
console.log(`\nWrote CHAIR_URLS + CHAIR_IMAGES → ${quizObjectsPath}`)

// ─── 3. GOODWIN CATALOG TEXT ────────────────────────────────────────────────────

const catalogText = buildGoodwinCatalogText()

const catalogFileContent = [
  '/**',
  ' * GOODWIN SERVER.JS — Chair Catalog Block',
  ' * Auto-generated by massagechairfinder/scripts/generate-goodwin.ts',
  ' *',
  ' * HOW TO USE:',
  ' *   In goodwin-chat-backend/server.js, find the QUIZ_PROMPT template literal.',
  ' *   Replace everything from "## COMPLETE CHAIR CATALOG" to the closing backtick',
  ' *   of QUIZ_PROMPT with the block below (the "## COMPLETE CHAIR CATALOG" header',
  ' *   is included in the block — paste it as the final section of QUIZ_PROMPT).',
  ' *',
  ' * The closing backtick of the QUIZ_PROMPT template literal goes AFTER this block.',
  ' */',
  '',
  catalogText,
].join('\n')

const catalogPath = join(outputDir, 'goodwin-catalog.txt')
writeFileSync(catalogPath, catalogFileContent, 'utf-8')
console.log(`Wrote Goodwin catalog text → ${catalogPath}`)

// ─── SUMMARY ────────────────────────────────────────────────────────────────────

const activeMcf    = GOODWIN_CHAIRS.filter(c => c.mcfActive !== false).length
const activeGoodwin = GOODWIN_CHAIRS.length
const withUrls     = lookupChairs.filter(c => c.affiliateUrl).length
const withImages   = lookupChairs.filter(c => c.goodwinImageUrl).length
const missingUrls  = lookupChairs.filter(c => !c.affiliateUrl).map(c => c.name)
const missingImages = lookupChairs.filter(c => !c.goodwinImageUrl).map(c => c.name)

console.log('\n── Summary ───────────────────────────────────────────────')
console.log(`Chairs in Goodwin catalog:  ${activeGoodwin}`)
console.log(`Chairs in MCF catalog:      ${activeMcf}`)
console.log(`Lookup entries generated:   ${lookupChairs.length}`)
console.log(`  With affiliate URL:       ${withUrls} / ${lookupChairs.length}`)
console.log(`  With Shopify image:       ${withImages} / ${lookupChairs.length}`)

if (missingUrls.length > 0) {
  console.log('\n⚠  Missing affiliate URLs (add to chairs.ts → affiliateUrl):')
  missingUrls.forEach(n => console.log(`   - ${n}`))
}

if (missingImages.length > 0) {
  console.log('\n⚠  Missing Shopify images (upload, then add to chairs.ts → goodwinImageUrl):')
  missingImages.forEach(n => console.log(`   - ${n}`))
}

console.log('\n── Next steps ────────────────────────────────────────────')
console.log('1. Copy CHAIR_URLS + CHAIR_IMAGES from scripts/goodwin-output/goodwin-quiz-objects.js')
console.log('   → Paste into eComm/goodwin-quiz-page.js (replace existing consts)')
console.log('2. Copy catalog text from scripts/goodwin-output/goodwin-catalog.txt')
console.log('   → Paste into goodwin-chat-backend/server.js (replace ## COMPLETE CHAIR CATALOG section)')
console.log('3. Commit goodwin-quiz-page.js and server.js in their respective repos.')
console.log('─────────────────────────────────────────────────────────\n')
